version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
      time: "03:20"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
      time: "03:10"
    groups:
      actions:
        patterns:
          - "*"
